# **INTRODUCTION TO NUMPY**

To convert list to array use function.

-   np.array()
-   np.asarray()
-   np.anyarray()

In [621]:
import numpy as np
l = [1,2,3,4]
a= np.array(l)
a1= np.asarray(l)
a2= np.asanyarray(l)
print (a,a1,a2)

[1 2 3 4] [1 2 3 4] [1 2 3 4]


In [622]:
c=a
c[0]=100
print (a)
print (c)

[100   2   3   4]
[100   2   3   4]


In above statement the process of deep copy and shallow copy is applied.
where both the varible are assign to the same object.


**Matrix**
-   Matrix is Subset of array.
-   Matrix is a 2D array.
-   Matrix is a collection of rows and columns.

In [623]:
l=[[1,2,3],[4,5,6],[7,8,9]]
b = np.matrix(l)
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**Creating a Array with diffrent Methods**

Lets create a Array with from function.

In [624]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In above code
-   Created a array using the Lamda.
-   Where 'i' represents the Row.
-   Where 'j' represents the Colum
-   (2,3) represrents size of the array, Here the size is 3 x 3, 3 row and 3 columnn



In [625]:
np.fromfunction(lambda i,j:i*j,(11,11)) # Here index are multiplied by each other & Multiplication Table is formed

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.],
       [  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.],
       [  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.],
       [  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.],
       [  0.,   6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.,  60.],
       [  0.,   7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.,  70.],
       [  0.,   8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.,  80.],
       [  0.,   9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.,  90.],
       [  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]])

Lets create a array using form iter (using iteration)

In [626]:
iterable = (i*i for i in range(5)) # Here we have created a iterable object
d=np.fromiter(iterable , int)
d

array([ 0,  1,  4,  9, 16])

Lets create a array using from string

In [627]:
np.fromstring('123 456 789',sep=" ")# Here first string is crated and used sperate function (sep=) to seprate the values


array([123., 456., 789.])

In [628]:
np.fromstring('1,2,3,4,5,6,7',sep=',')

array([1., 2., 3., 4., 5., 6., 7.])

**Numpy-Functions**

In [629]:
l =[1,2,3,4,5,6]
arr = np.array(l)

To check the Dimension of Array

In [630]:
arr.ndim # Its a 1-D array

1

In [631]:
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9]]) #Its a 2-D Array
arr1.ndim

2

To check size of Array

In [632]:
arr.size # .size is used to check the size

6

In [633]:
arr1.size

9

To check shape of array.

In [634]:
arr.shape # .shape is to used to check the shape of the array

(6,)

In [635]:
arr1.shape # this is 2-D array so the shape will be (row,column)

(3, 3)

To check the Data Type in the array.

In [636]:
arr.dtype # By using Dtype function 

dtype('int32')

Creating data using range function.

In [637]:
np.arange(2,14) #same as for loop range function.

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [638]:
np.arange(1.1,5.6) # you can also use float values.

array([1.1, 2.1, 3.1, 4.1, 5.1])

In [639]:
np.arange(1.1,2,0.1) # you can also add steps, similar to the slicing or range in loops
# (Start-point, End-point, Step)

array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [640]:
list(np.arange(1.1,2,0.1)) # Converting in into a list.

[1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000004,
 1.5000000000000004,
 1.6000000000000005,
 1.7000000000000006,
 1.8000000000000007,
 1.9000000000000008]

Creating a data using line space

In [641]:
np.linspace(1,5,10) #it will create a raandom data between 1 to 5 , needed data is 10

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Creating a data using **zeros** function

In [642]:
np.zeros(5) # It will create 1-D array using the zeros.

array([0., 0., 0., 0., 0.])

In [643]:
np.zeros((3,4)) # It will create 2-D array using zeros.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [644]:
np.zeros((2,3,4)) #It will create 3-D array using zeros.
# it can be redable as 2 arrays of 3 by 4
# Eg: The Structure is Just like a book.
# Where page 1 is one array and page 2 is another array inn  the z-axis

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Creating a data using **ones** function

In [645]:
np.ones(5) # It will create a Array using ones.

array([1., 1., 1., 1., 1.])

In [646]:
np.ones((2,5)) # It will create a 2-D array using ones.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [647]:
np.ones((2,6,5)) # It will createb a 3-D array just like zeros.

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

Performing arthematic operation on  a array.

In [648]:
ar=np.ones((3,4))
ar + 2 # it will add 2 will every value avaible in  the array

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [649]:
ar * 5 # It will add 5 with every Values.

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

Creating an  empty array

In [650]:
np.empty(2) # It will give you a random values

array([4.24399163e-314, 8.48798317e-314])

In [651]:
np.empty((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Creating a array using eye function.
-   It will create a Identity matrix.
-   All sides are same in this matrix.

In [652]:
np.eye(5) # It will create a 5x5 Identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Creating a random data. 

In [653]:
np.random.randn(3,5) # It will generate a random data.where the means is zero & standard devaition  is 1.

array([[ 2.9325488 , -0.32768133, -1.28791208,  0.19037175, -0.43796628],
       [-0.09428048,  0.25319302,  0.72594467, -0.13520076, -0.6368286 ],
       [ 0.39962934, -0.4933953 , -1.15300146, -0.16498216,  1.3774384 ]])

In [654]:
np.random.rand(3,5) # It will generate a randon data.

array([[0.94514345, 0.82230168, 0.16161015, 0.30992548, 0.95668853],
       [0.43779335, 0.16670361, 0.50153533, 0.56345613, 0.28191064],
       [0.48360965, 0.92933562, 0.74784418, 0.33422217, 0.83999224]])

In [655]:
np.random.randint (5,50,(5,5)) # It will gerrate the random data between 5 to 50, and size is 5x5

array([[41, 43,  8, 42, 44],
       [24,  5,  8, 43, 16],
       [44,  6, 34,  7, 16],
       [25, 22, 15,  7, 48],
       [ 5, 21, 12, 27, 23]])

Reshaping the data 

In [656]:
arr = np.random.randn(3,4) # the Data is 3x4 
print(arr)
arr.reshape(6,2) # shape converted into 6x2
# Note: the data size must be the same after reshaping.


[[ 0.55053852 -0.09842872  0.68158644  0.12603993]
 [-0.84071824  0.99896476 -1.17776395 -0.68768883]
 [ 0.98936432  1.49389813 -1.81831223  1.37551927]]


array([[ 0.55053852, -0.09842872],
       [ 0.68158644,  0.12603993],
       [-0.84071824,  0.99896476],
       [-1.17776395, -0.68768883],
       [ 0.98936432,  1.49389813],
       [-1.81831223,  1.37551927]])

Extracting the data

In [657]:
arr[2][1]

1.493898130336519

Extracting multiple data

In [658]:
arr[0:2,2]# Data is extracted from row 1&2 of column 3. [row starting index : row end point ,column index]

array([ 0.68158644, -1.17776395])

Extracting Specified data with condition

In [659]:
arr1 = np.random.randint(1,100,(5,5))
print(arr1)
arr1[arr1>50]

[[90 24 17 41 59]
 [81 43 17 23 44]
 [95  4 66 39  8]
 [52 77 20 89 12]
 [81 57 46 82 82]]


array([90, 59, 81, 95, 66, 52, 77, 89, 81, 57, 82, 82])

Extract the specific data

In [660]:
arr1[1:3,[2,3,4]] #here extracted the data from row 2 & 3 and column 3,4 & 5

array([[17, 23, 44],
       [66, 39,  8]])

Modifying the data 

In [661]:
arr1 [0][0]=1000
arr1

array([[1000,   24,   17,   41,   59],
       [  81,   43,   17,   23,   44],
       [  95,    4,   66,   39,    8],
       [  52,   77,   20,   89,   12],
       [  81,   57,   46,   82,   82]])

Functions in Array.

In [662]:
ar1 = np.random.randint(1,10,(3,3))
ar2 = np.random.randint(1,10,(3,3))
ar1,ar2

(array([[8, 6, 8],
        [9, 5, 7],
        [2, 1, 3]]),
 array([[2, 8, 6],
        [8, 7, 5],
        [6, 1, 7]]))

Adding 2 array

In [663]:
ar1+ar2

array([[10, 14, 14],
       [17, 12, 12],
       [ 8,  2, 10]])

Substracting Two array

In [664]:
ar1 - ar2

array([[ 6, -2,  2],
       [ 1, -2,  2],
       [-4,  0, -4]])

Multiplying Two Arrays

In [665]:
ar1 * ar2

array([[16, 48, 48],
       [72, 35, 35],
       [12,  1, 21]])

Matrix Multiplication 

In [666]:
ar1 @ ar2 # Use '@' symbol for matrix multiplication

array([[112, 114, 134],
       [100, 114, 128],
       [ 30,  26,  38]])

Add ar1 by 10

In [667]:
ar1 +100

array([[108, 106, 108],
       [109, 105, 107],
       [102, 101, 103]])

Substracting ar1 by 10

In [668]:
ar1 -2

array([[ 6,  4,  6],
       [ 7,  3,  5],
       [ 0, -1,  1]])

Multiplying ar1 by 5

In [669]:
ar1 * 5

array([[40, 30, 40],
       [45, 25, 35],
       [10,  5, 15]])

ar1 to the power of 2

In [670]:
ar1 ** 2

array([[64, 36, 64],
       [81, 25, 49],
       [ 4,  1,  9]])

**BROADCASTING IN NUMPY**

In [671]:
arr = np.zeros((4,4))
row = np.array([2,4,6,8])


Row wise broadcasting

In [672]:
arr + row

array([[2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.]])

Column wise Broadcasting

In [673]:
col = np.array([[2,4,6,8]]).T
col.T # T for transposing the array (Rotating the array)
arr  + col


array([[2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [8., 8., 8., 8.]])

In [674]:
arr = np.random.randint(1,16,(3,3))

Taking Sqare root of array

In [675]:
np.sqrt(arr)

array([[3.74165739, 1.41421356, 2.23606798],
       [3.16227766, 1.73205081, 2.23606798],
       [2.        , 1.41421356, 3.87298335]])

Getting Exponent 

In [676]:
np.exp(arr)

array([[1.20260428e+06, 7.38905610e+00, 1.48413159e+02],
       [2.20264658e+04, 2.00855369e+01, 1.48413159e+02],
       [5.45981500e+01, 7.38905610e+00, 3.26901737e+06]])

Getting Log

In [677]:
np.log(arr)

array([[2.63905733, 0.69314718, 1.60943791],
       [2.30258509, 1.09861229, 1.60943791],
       [1.38629436, 0.69314718, 2.7080502 ]])

**DATA MANUPULATION**

In [678]:
arr = np.random.randint(5,20,(3,4))
arr

array([[ 8, 10, 13, 12],
       [16,  8, 10,  9],
       [15, 13, 15, 16]])

Manupulating Shape of Array

In [679]:
arr.reshape(6,2)


array([[ 8, 10],
       [13, 12],
       [16,  8],
       [10,  9],
       [15, 13],
       [15, 16]])

In [680]:
arr.reshape(2,6)

array([[ 8, 10, 13, 12, 16,  8],
       [10,  9, 15, 13, 15, 16]])

Transposing the array

In [681]:
arr.T

array([[ 8, 16, 15],
       [10,  8, 13],
       [13, 10, 15],
       [12,  9, 16]])

Manupulating 2D array to 1D

In [682]:
arr.flatten()

array([ 8, 10, 13, 12, 16,  8, 10,  9, 15, 13, 15, 16])

Manupulating Row to column

In [683]:
arr1=np.array([1,2,3,4,5])
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Manupulatating 1D row to 2D

In [684]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

Squeeze the Array 
-    Combining the single elements in 1D array

In [685]:
data =np.array([[1],[2],[3],[4]])
np.squeeze(data)

array([1, 2, 3, 4])

Repeating the elements in array

In [686]:
np.repeat(data,3) #Repeating the array 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

Rolling the elements in the array.
- rotating or shifting the places in the array.

In [687]:
np.roll(data,2)

array([[3],
       [4],
       [1],
       [2]])

Diaganoal function for Manupulation
- Tranfer the 1D data to the 2D in diagonally

In [688]:
arr=np.array([1, 2, 3, 4])
np.diag(arr)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

**STRING FUNCTION IN NUMPY**

In [689]:
arr = np.array(["Darshan","Dalvi"])
arr

array(['Darshan', 'Dalvi'], dtype='<U7')

Basic String operation

In [690]:
np.char.upper(arr)

array(['DARSHAN', 'DALVI'], dtype='<U7')

In [691]:
np.char.lower(arr)

array(['darshan', 'dalvi'], dtype='<U7')

In [692]:
np.char.capitalize(arr)

array(['Darshan', 'Dalvi'], dtype='<U7')